version: '2'
services:
  postgres:
    image: postgres:10.4
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "5432:5432"
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
  php:
    build: docker
    restart: always
    environment:
      - DB_HOST=postgres
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=5432
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./app:/app
