<h1>Other error</h1>
<h2><?php echo get_class($this->exception); ?></h2>
<dl>
    <dt>File:</dt>
    <dd>
        <pre><?php echo $this->exception->getFile() ?>:<?php echo $this->exception->getLine() ?></pre>
    </dd>
    <dt>Message:</dt>
    <dd>
        <pre><?php echo $this->exception->getMessage() ?></pre>
    </dd>
    <dt>Stack trace:</dt>
    <dd>
        <pre><?php echo $this->exception->getTraceAsString() ?></pre>
    </dd>
</dl>
